//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCardMaster.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCardMaster.i18n.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received a copy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators:
        ///       Turkish - Çigdem Çavus
        ///       Spanish - Gabriel Reyes.
        /// </summary>
        internal static string AboutTranslators {
            get {
                return ResourceManager.GetString("AboutTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields.
        /// </summary>
        internal static string AllFields {
            get {
                return ResourceManager.GetString("AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and show back side for.
        /// </summary>
        internal static string AndShowBackSideFor {
            get {
                return ResourceManager.GetString("AndShowBackSideFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string Animate {
            get {
                return ResourceManager.GetString("Animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Filetypes.
        /// </summary>
        internal static string AssociateFiletypes {
            get {
                return ResourceManager.GetString("AssociateFiletypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as: {0}.
        /// </summary>
        internal static string BatchEditInstruction {
            get {
                return ResourceManager.GetString("BatchEditInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field count does not match..
        /// </summary>
        internal static string BatchEditMismatchException {
            get {
                return ResourceManager.GetString("BatchEditMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Entry.
        /// </summary>
        internal static string BatchEntry {
            get {
                return ResourceManager.GetString("BatchEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string BottomCenter {
            get {
                return ResourceManager.GetString("BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Left.
        /// </summary>
        internal static string CenterLeft {
            get {
                return ResourceManager.GetString("CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Right.
        /// </summary>
        internal static string CenterRight {
            get {
                return ResourceManager.GetString("CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        internal static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}
        ///
        ///This program is made possible by the following contributors:
        ///     Magic Control Library 1.7.4.0:  Phil Wright &lt;http://www.dotnetmagic.com/&gt;
        ///     Tango Icon Project &lt;http://tango.freedesktop.org/&gt;
        ///     Drag Drop ListView: Matt Hawley &lt;http://www.codeproject.com/cs/miscctrl/DragAndDropListView.asp&gt;
        ///     CSV Reader 3.1.2: Sébastien Lorion &lt;http://www.codeproject.com/cs/database/CsvReader.asp&gt;.
        /// </summary>
        internal static string ContributorsFormat {
            get {
                return ResourceManager.GetString("ContributorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The csv file might be corrupt or invalid.
        /// </summary>
        internal static string CorruptCsvFileMessage {
            get {
                return ResourceManager.GetString("CorruptCsvFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file might be corrupt or invalid.
        /// </summary>
        internal static string CorruptFileMessage {
            get {
                return ResourceManager.GetString("CorruptFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Separator.
        /// </summary>
        internal static string CSVSeperator {
            get {
                return ResourceManager.GetString("CSVSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV separator is used by the batch editor to separate fields and also by &apos;Export as CSV&apos; method..
        /// </summary>
        internal static string CSVSeperatorHint {
            get {
                return ResourceManager.GetString("CSVSeperatorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be read. It might be corrupt or invalid.
        /// </summary>
        internal static string DeSerializationFailedMessage {
            get {
                return ResourceManager.GetString("DeSerializationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Card.
        /// </summary>
        internal static string DesignCard {
            get {
                return ResourceManager.GetString("DesignCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action may cause loss of data.
        ///It is recomended that you make a backup copy before proceeding.
        ///Continue with Delete?.
        /// </summary>
        internal static string DesignerDataLossWarning {
            get {
                return ResourceManager.GetString("DesignerDataLossWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cards.
        /// </summary>
        internal static string EditCards {
            get {
                return ResourceManager.GetString("EditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Edit Multiple Items].
        /// </summary>
        internal static string EditMultipleItems {
            get {
                return ResourceManager.GetString("EditMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;&apos;&apos;+&apos;&apos;&apos; to add a new card..
        /// </summary>
        internal static string EditorNoCardsMessage {
            get {
                return ResourceManager.GetString("EditorNoCardsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save backups of open files..
        /// </summary>
        internal static string EnableBackupOption {
            get {
                return ResourceManager.GetString("EnableBackupOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end the test?.
        /// </summary>
        internal static string EndTestQuestion {
            get {
                return ResourceManager.GetString("EndTestQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string fBatchEditInstructionField {
            get {
                return ResourceManager.GetString("fBatchEditInstructionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data will be lost when saved to {0} format. To preserve the data, save in a different format..
        /// </summary>
        internal static string fDataLossWarning {
            get {
                return ResourceManager.GetString("fDataLossWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of fields do not match. Read help for more information.
        /// </summary>
        internal static string FieldMismatchMessage {
            get {
                return ResourceManager.GetString("FieldMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name cannot contain the space character..
        /// </summary>
        internal static string FieldNameContainsSpace {
            get {
                return ResourceManager.GetString("FieldNameContainsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        internal static string FieldNameEmptyError {
            get {
                return ResourceManager.GetString("FieldNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names must be unique. Another field by this name already exist..
        /// </summary>
        internal static string FieldNameNotUnique {
            get {
                return ResourceManager.GetString("FieldNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist.
        /// </summary>
        internal static string FileNotExistMessage {
            get {
                return ResourceManager.GetString("FileNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handlers are implemented for type {0}.
        ///Unable to create handler for &apos;{1}&apos;.
        /// </summary>
        internal static string FileNotSupportedMessage {
            get {
                return ResourceManager.GetString("FileNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This error might be caused by incorrect file extension..
        /// </summary>
        internal static string FileNotSupportedMessageHint {
            get {
                return ResourceManager.GetString("FileNotSupportedMessageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - [{1}].
        /// </summary>
        internal static string fMainWindowTitle {
            get {
                return ResourceManager.GetString("fMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review - {0} of {1} - {2}.
        /// </summary>
        internal static string fReviewer {
            get {
                return ResourceManager.GetString("fReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes made to &apos;{0}&apos;. Save now?.
        /// </summary>
        internal static string fSaveChangesQuestion {
            get {
                return ResourceManager.GetString("fSaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scored {0} out of {1} ({2:#.#}%).
        /// </summary>
        internal static string fTestResults {
            get {
                return ResourceManager.GetString("fTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open &apos;{0}&apos;.
        ///{1}..
        /// </summary>
        internal static string fUnableToOpenMessage {
            get {
                return ResourceManager.GetString("fUnableToOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0})
        ///  Details:{1}.
        /// </summary>
        internal static string GenericOpenErrorMessage {
            get {
                return ResourceManager.GetString("GenericOpenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality text layout (Slow)..
        /// </summary>
        internal static string HqTextLayoutOption {
            get {
                return ResourceManager.GetString("HqTextLayoutOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Export.
        /// </summary>
        internal static string HtmlExport {
            get {
                return ResourceManager.GetString("HtmlExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you do not have a printer installed. You need to install a printer before using this feature..
        /// </summary>
        internal static string InvalidPrinterError {
            get {
                return ResourceManager.GetString("InvalidPrinterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep text styles when exporting to HTML..
        /// </summary>
        internal static string KeepStylesInHtmlMessage {
            get {
                return ResourceManager.GetString("KeepStylesInHtmlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use [Ctrl] + [Enter] to enter a line break..
        /// </summary>
        internal static string LineBreakHint {
            get {
                return ResourceManager.GetString("LineBreakHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually duplex when printing (Allows you to print on both sides of the page)..
        /// </summary>
        internal static string ManualDuplexOption {
            get {
                return ResourceManager.GetString("ManualDuplexOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Batch Add.
        /// </summary>
        internal static string MenuBatchAdd {
            get {
                return ResourceManager.GetString("MenuBatchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chec&amp;k All.
        /// </summary>
        internal static string MenuCheckAll {
            get {
                return ResourceManager.GetString("MenuCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dele&amp;te.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desi&amp;gn.
        /// </summary>
        internal static string MenuDesign {
            get {
                return ResourceManager.GetString("MenuDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open As &amp;Design....
        /// </summary>
        internal static string MenuOpenAsDesign {
            get {
                return ResourceManager.GetString("MenuOpenAsDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa&amp;ge Setup....
        /// </summary>
        internal static string MenuPageSetup {
            get {
                return ResourceManager.GetString("MenuPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre&amp;ferences.
        /// </summary>
        internal static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recent Files.
        /// </summary>
        internal static string MenuRecentFiles {
            get {
                return ResourceManager.GetString("MenuRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;view.
        /// </summary>
        internal static string MenuReview {
            get {
                return ResourceManager.GetString("MenuReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;Design As....
        /// </summary>
        internal static string MenuSaveDesignAs {
            get {
                return ResourceManager.GetString("MenuSaveDesignAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Te&amp;st.
        /// </summary>
        internal static string MenuTakeTest {
            get {
                return ResourceManager.GetString("MenuTakeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchec&amp;k All.
        /// </summary>
        internal static string MenuUnCheckAll {
            get {
                return ResourceManager.GetString("MenuUnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file format is does not have any card design information associated with it.
        ///Use &apos;Designer&apos; to design the card..
        /// </summary>
        internal static string MissingStyleInfoMessage {
            get {
                return ResourceManager.GetString("MissingStyleInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both &quot;{0}&quot; and &quot;{1}&quot; fields are marked as &apos;Answer&apos;. Only one field should be &apos;Answer&apos;. This may cause problems later. Do you want to correct this?.
        /// </summary>
        internal static string MultipleAnswerTypeError {
            get {
                return ResourceManager.GetString("MultipleAnswerTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both &quot;{0}&quot; and &quot;{1}&quot; fields are marked as &apos;Key&apos;. Only one field should be &apos;Key&apos;. This may cause problems later. Do you want to correct this?.
        /// </summary>
        internal static string MultipleKeyTypeError {
            get {
                return ResourceManager.GetString("MultipleKeyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Choice Test.
        /// </summary>
        internal static string MutipleChoiceTest {
            get {
                return ResourceManager.GetString("MutipleChoiceTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current deck does not have the &apos;Key&apos; or the &apos;Answer&apos; fields, which are needed to save as {0}. Please save in a different format or modify the deck using the Card Designer..
        /// </summary>
        internal static string NeedKeyAnswer {
            get {
                return ResourceManager.GetString("NeedKeyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deck.
        /// </summary>
        internal static string NewDeck {
            get {
                return ResourceManager.GetString("NewDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Design.
        /// </summary>
        internal static string NewDesign {
            get {
                return ResourceManager.GetString("NewDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cards to print.
        /// </summary>
        internal static string NoCardToPrintMessage {
            get {
                return ResourceManager.GetString("NoCardToPrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup of &apos;{0}&apos; exists that is more recent. Do you want to open the backup?.
        /// </summary>
        internal static string OpenBackupQuestion {
            get {
                return ResourceManager.GetString("OpenBackupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cards you are trying to paste have more fields than the current deck. Add {0} more fields using the designer and try again..
        /// </summary>
        internal static string PasteFieldMismatchPlural {
            get {
                return ResourceManager.GetString("PasteFieldMismatchPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cards you are trying to paste have more field than the current deck. Add {0} more field using the designer and try again..
        /// </summary>
        internal static string PasteFieldMismatchSingular {
            get {
                return ResourceManager.GetString("PasteFieldMismatchSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer you selected cannot duplex. Do you want to manually duplex?.
        /// </summary>
        internal static string PrinterCannotDuplex {
            get {
                return ResourceManager.GetString("PrinterCannotDuplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Font:.
        /// </summary>
        internal static string PrintFont {
            get {
                return ResourceManager.GetString("PrintFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Previe&amp;w.
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current deck does not have the &apos;Key&apos; and &apos;Answer&apos; fields defined. You can correct this by editing the deck using Card Designer..
        /// </summary>
        internal static string QuizDeckInvalid {
            get {
                return ResourceManager.GetString("QuizDeckInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 4 cards in order to run the quiz..
        /// </summary>
        internal static string QuizMinCardMessage {
            get {
                return ResourceManager.GetString("QuizMinCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Cards - Shuffled.
        /// </summary>
        internal static string ReviewCardsShuffled {
            get {
                return ResourceManager.GetString("ReviewCardsShuffled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Delays:.
        /// </summary>
        internal static string ReviewDelays {
            get {
                return ResourceManager.GetString("ReviewDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        internal static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate Card Flip and Switch.
        /// </summary>
        internal static string ReviewerAnimateTT {
            get {
                return ResourceManager.GetString("ReviewerAnimateTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Card.
        /// </summary>
        internal static string ReviewerFlipCardTT {
            get {
                return ResourceManager.GetString("ReviewerFlipCardTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned.
        /// </summary>
        internal static string ReviewerLearnedTT {
            get {
                return ResourceManager.GetString("ReviewerLearnedTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Review.
        /// </summary>
        internal static string ReviewerNeedsReviewTT {
            get {
                return ResourceManager.GetString("ReviewerNeedsReviewTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Card.
        /// </summary>
        internal static string ReviewerNextCardTT {
            get {
                return ResourceManager.GetString("ReviewerNextCardTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer - No Cards.
        /// </summary>
        internal static string ReviewerNoCards {
            get {
                return ResourceManager.GetString("ReviewerNoCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Learned.
        /// </summary>
        internal static string ReviewerNotLearnedTT {
            get {
                return ResourceManager.GetString("ReviewerNotLearnedTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Card.
        /// </summary>
        internal static string ReviewerPreviousCardTT {
            get {
                return ResourceManager.GetString("ReviewerPreviousCardTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Timer.
        /// </summary>
        internal static string ReviewerToggleTT {
            get {
                return ResourceManager.GetString("ReviewerToggleTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&apos;&apos;No Cards To Review&apos;&apos;&apos;.
        /// </summary>
        internal static string ReviewNoCardsMessage {
            get {
                return ResourceManager.GetString("ReviewNoCardsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save now?.
        /// </summary>
        internal static string SaveNowQuestion {
            get {
                return ResourceManager.GetString("SaveNowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options.
        /// </summary>
        internal static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsL {
            get {
                return ResourceManager.GetString("SecondsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show front side for.
        /// </summary>
        internal static string ShowFrontSideFor {
            get {
                return ResourceManager.GetString("ShowFrontSideFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffled.
        /// </summary>
        internal static string Shuffled {
            get {
                return ResourceManager.GetString("Shuffled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sides.
        /// </summary>
        internal static string Sides {
            get {
                return ResourceManager.GetString("Sides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        internal static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string TopCenter {
            get {
                return ResourceManager.GetString("TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string TopLeft {
            get {
                return ResourceManager.GetString("TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        internal static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files of type {0} is not supported. Try a supported file type..
        /// </summary>
        internal static string UnsupportedFormat {
            get {
                return ResourceManager.GetString("UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}
        ///Written by Nithin Philips &lt;spikiermonkey@users.sourceforge.net&gt;.
        ///
        ///Copyright (C) 2003-2008 Nithin Philips.
        ///This is free software; There is NO warranty
        ///not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        ///
        ///Read COPYING in application directory or visit http://www.gnu.org/copyleft/gpl.html for more info..
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only save to this format, it cannot be opened. A copy will be saved to {0}..
        /// </summary>
        internal static string WriteOnlyFormatWarning {
            get {
                return ResourceManager.GetString("WriteOnlyFormatWarning", resourceCulture);
            }
        }
    }
}
