/*
 * Warning: This file was autogenerated.
 *          Modification will be lost when overwritten.
 */

// $Id: AssemblyInfo.cs 168 2008-02-14 02:04:24Z spikiermonkey $

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Flash Card Master")]
[assembly: AssemblyDescription("Program to Create, Edit and Print flash cards")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nithin Philips")]
[assembly: AssemblyProduct("Flash Card Master")]
[assembly: AssemblyCopyright("(C) 2003-2008 Nithin Philips")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]